// <auto-generated />
using System;
using HotelManagementSystemII.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystemII.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("HotelManagementSystemII.Entity.Customer", b =>
                {
                    b.Property<Guid>("CsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("NICNO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoomRID")
                        .HasColumnType("TEXT");

                    b.HasKey("CsId");

                    b.HasIndex("RoomRID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Employee", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserAccountID")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdentityId");

                    b.HasIndex("UserAccountID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Room", b =>
                {
                    b.Property<Guid>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("RBed")
                        .HasColumnType("TEXT");

                    b.Property<string>("RNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RStatusRID")
                        .HasColumnType("TEXT");

                    b.HasKey("RID");

                    b.HasIndex("RStatusRID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.RoomStatus", b =>
                {
                    b.Property<Guid>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Available")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("RNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("RID");

                    b.ToTable("RoomStatus");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.UserAccount", b =>
                {
                    b.Property<int>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserAccountID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Customer", b =>
                {
                    b.HasOne("HotelManagementSystemII.Entity.Room", "Room")
                        .WithMany("Customer")
                        .HasForeignKey("RoomRID");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Employee", b =>
                {
                    b.HasOne("HotelManagementSystemII.Entity.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountID");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Room", b =>
                {
                    b.HasOne("HotelManagementSystemII.Entity.RoomStatus", "RStatus")
                        .WithMany()
                        .HasForeignKey("RStatusRID");

                    b.Navigation("RStatus");
                });

            modelBuilder.Entity("HotelManagementSystemII.Entity.Room", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
